# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - dmnfusion

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:


  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5B1DDF4C436D4ACCBFE92FBCD87F3AB9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C10F8A671A114664929E47BE681728B8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_83D3DC4FFEB74BE7B11FEE158A79D9B2 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dmnfusion'
          slot-name: 'Production'
          package: .
          
